apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - vault-connection.yaml
  - vault-auth.yaml
  - aireye-app-secret.yaml
  - aireye-genai-secret.yaml
  - litellm-secret.yaml
  - vault-secret.yaml
  - pg-secret.yaml
  - redis-secret.yaml
  - minio-secret.yaml
  - kc-secret.yaml
  - oidc-secret.yaml
  - litellm-oidc-secret.yaml
