apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: litellm-oidc-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/oidc
  refreshAfter: 30s
  destination:
    name: litellm-oidc-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        GENERIC_CLIENT_ID:
          text: '{{ get .Secrets "OIDC_CLIENT_ID" }}'
        GENERIC_CLIENT_SECRET:
          text: '{{ get .Secrets "OIDC_CLIENT_SECRET" }}'
        GENERIC_AUTHORIZATION_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/auth
        GENERIC_TOKEN_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/token
        GENERIC_USERINFO_ENDPOINT:
          text: https://keycloak.lowjungxuan.dpdns.org/realms/master/protocol/openid-connect/userinfo
        GENERIC_SCOPE:
          text: openid profile email
