apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/minio
  refreshAfter: 30s
  destination:
    name: minio-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: StatefulSet
      name: minio
