apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pg-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/pg
  refreshAfter: 30s
  destination:
    name: pg-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        POSTGRES_USER:
          text: '{{ get .Secrets "PG_USER" }}'
        POSTGRES_PASSWORD:
          text: '{{ get .Secrets "PG_PASSWORD" }}'
        POSTGRES_DB:
          text: '{{ get .Secrets "PG_DB" }}'
  rolloutRestartTargets:
    - kind: StatefulSet
      name: postgres
    - kind: Deployment
      name: keycloak
