apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: redis-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/redis
  refreshAfter: 30s
  destination:
    name: redis-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: StatefulSet
      name: redis
