apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/vault
  refreshAfter: 30s
  destination:
    name: vault-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      excludes:
        - .*
      templates:
        VAULT_PG_CONNECTION_URL:
          text: '{{ get .Secrets "VAULT_PG_CONNECTION_URL" }}'
