apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: aireye-cluster/grafana
  refreshAfter: 30s
  destination:
    name: grafana-secret
    create: true
    overwrite: true
  rolloutRestartTargets:
    - kind: Deployment
      name: kube-prometheus-stack-grafana
