apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.16.6
    helm:
      releaseName: promtail
      values: |
        config:
          clients:
            - url: http://loki.infra.svc.cluster.local:3100/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
            scrapeConfigs: |
              - job_name: kubernetes-pods
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - infra
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: drop
                    regex: "false"
                  - source_labels: [__meta_kubernetes_pod_label_app]
                    target_label: app
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    target_label: pod
                  - source_labels: [__meta_kubernetes_container_name]
                    target_label: container
                  - replacement: /var/log/pods/*$1/*.log
                    separator: /
                    source_labels:
                      - __meta_kubernetes_pod_uid
                      - __meta_kubernetes_pod_container_name
                    target_label: __path__
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            effect: NoSchedule
        rbac:
          create: true
          pspEnabled: false
        serviceAccount:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
